EMOTE_DICT = {
   "Zombie": ["idle_zombie", 28.75, False],
   "Relaxed": ["sit-relaxed", 29.89, False],
   "Attentive": ["idle_layingdown", 24.58, False],
   "Sleepy": ["idle-loop-tired", 21.96, False],
   "Pouty Face": ["idle-sad", 24.38, False],
   "Posh": ["idle-posh", 21.85, False],
   "Tap Loop": ["idle-loop-tapdance", 6.26, False],
   "Sit": ["idle-loop-sitfloor", 22.32, True],
   "Shy": ["emote-shy", 4.48, True],
   "Bummed": ["idle-loop-sad", 6.05, False],
   "Chillin'": ["idle-loop-happy", 18.80, False],
   "Annoyed": ["idle-loop-annoyed", 17.06, False],
   "Aerobics": ["idle-loop-aerobics", 8.51, False],
   "Ponder": ["idle-lookup", 22.34, False],
   "Hero Pose": ["idle-hero", 21.88, False],
   "Relaxing": ["idle-floorsleeping2", 17.25, False],
   "Cozy Nap": ["idle-floorsleeping", 13.94, False],
   "Enthused": ["idle-enthusiastic", 15.94, True],
   "Boogie Swing": ["idle-dance-swinging", 13.20, False],
   "Feel The Beat": ["idle-dance-headbobbing", 25.37, False],
   "Irritated": ["idle-angry", 25.43, False],
   "Yes": ["emote-yes", 2.57, True],
   "I Believe I Can Fly": ["emote-wings", 13.13, False],
   "The Wave": ["emote-wave", 2.69, True],
   "Tired": ["emote-tired", 4.61, True],
   "Think": ["emote-think", 3.69, False],
   "Theatrical": ["emote-theatrical", 8.59, False],
   "Tap Dance": ["emote-tapdance", 11.06, False],
   "Super Run": ["emote-superrun", 6.27, False],
   "Super Punch": ["emote-superpunch", 3.75, False],
   "Sumo Fight": ["emote-sumo", 10.87, False],
   "Thumb Suck": ["emote-suckthumb", 4.19, False],
   "Splits Drop": ["emote-splitsdrop", 4.47, False],
   "Snowball Fight!": ["emote-snowball", 5.23, True],
   "Snow Angel": ["emote-snowangel", 6.22, True],
   "Secret Handshake": ["emote-secrethandshake", 3.88, False],
   "Sad": ["emote-sad", 5.41, True],
   "Rope Pull": ["emote-ropepull", 8.77, False],
   "Roll": ["emote-roll", 3.56, False],
   "ROFL!": ["emote-rofl", 6.31, False],
   "Robot": ["emote-robot", 7.61, False],
   "Rainbow": ["emote-rainbow", 2.81, False],
   "Proposing": ["emote-proposing", 4.28, False],
   "Peekaboo!": ["emote-peekaboo", 3.63, False],
   "Peace": ["emote-peace", 5.76, False],
   "Panic": ["emote-panic", 2.85, False],
   "No": ["emote-no", 2.70, True],
   "Ninja Run": ["emote-ninjarun", 4.75, False],
   "Night Fever": ["emote-nightfever", 5.49, False],
   "Monster Fail": ["emote-monster_fail", 4.63, False],
   "Model": ["emote-model", 6.49, True],
   "Flirty Wave": ["emote-lust", 4.66, True],
   "Level Up!": ["emote-levelup", 6.05, False],
   "Amused": ["emote-laughing2", 5.06, False],
   "Laugh": ["emote-lagughing", 1.13, False],
   "Kiss": ["emote-kiss", 2.39, True],
   "Super Kick": ["emote-kicking", 4.87, False],
   "Jump": ["emote-jumpb", 3.58, False],
   "Judo Chop": ["emote-judochop", 2.43, False],
   "Imaginary Jetpack": ["emote-jetpack", 16.76, False],
   "Hug Yourself": ["emote-hugyourself", 4.99, False],
   "Sweating": ["emote-hot", 4.35, True],
   "Hero Entrance": ["emote-hero", 5.00, False],
   "Hello": ["emote-hello", 2.73, True],
   "Headball": ["emote-headball", 10.07, False],
   "Harlem Shake": ["emote-harlemshake", 13.56, False],
   "Happy": ["emote-happy", 3.48, False],
   "Handstand": ["emote-handstand", 4.02, False],
   "Greedy Emote": ["emote-greedy", 4.64, True],
   "Graceful": ["emote-graceful", 3.75, False],
   "Moonwalk": ["emote-gordonshuffle", 8.05, False],
   "Ghost Float": ["emote-ghost-idle", 19.57, False],
   "Gangnam Style": ["emote-gangnam", 7.28, False],
   "Frolic ": ["emote-frollicking", 3.70, False],
   "Faint": ["emote-fainting", 18.42, False],
   "Clumsy": ["emote-fail2", 6.48, False],
   "Fall": ["emote-fail1", 5.62, False],
   "Face Palm": ["emote-exasperatedb", 2.72, True],
   "Exasperated": ["emote-exasperated", 2.37, False],
   "Elbow Bump": ["emote-elbowbump", 3.80, False],
   "Disco": ["emote-disco", 5.37, False],
   "Blast Off": ["emote-disappear", 6.20, False],
   "Faint Drop": ["emote-deathdrop", 3.76, False],
   "Collapse": ["emote-death2", 4.86, False],
   "Revival": ["emote-death", 6.62, False],
   "Dab": ["emote-dab", 2.72, False],
   "Curtsy": ["emote-curtsy", 2.43, True],
   "Confusion": ["emote-confused", 8.58, True],
   "Cold": ["emote-cold", 3.66, False],
   "Charging": ["emote-charging", 8.03, True],
   "Bunny Hop": ["emote-bunnyhop", 12.38, False],
   "Bow": ["emote-bow", 3.34, True],
   "Boo": ["emote-boo", 4.50, False],
   "Home Run!": ["emote-baseball", 7.25, False],
   "Falling Apart": ["emote-apart", 4.81, False],
   "Thumbs Up": ["emoji-thumbsup", 2.70, True],
   "Point": ["emoji-there", 2.06, False],
   "Sneeze": ["emoji-sneeze", 3.00, False],
   "Smirk": ["emoji-smirking", 4.82, False],
   "Sick": ["emoji-sick", 5.07, False],
   "Gasp": ["emoji-scared", 3.01, False],
   "Punch": ["emoji-punch", 1.76, False],
   "Pray": ["emoji-pray", 4.50, False],
   "Stinky": ["emoji-poop", 4.80, False],
   "Naughty": ["emoji-naughty", 4.28, False],
   "Mind Blown": ["emoji-mind-blown", 2.40, False],
   "Lying": ["emoji-lying", 6.31, False],
   "Levitate": ["emoji-halo", 5.84, False],
   "Fireball Lunge": ["emoji-hadoken", 2.72, False],
   "Give Up": ["emoji-give-up", 5.41, False],
   "Tummy Ache": ["emoji-gagging", 5.50, True],
   "Flex": ["emoji-flex", 2.10, True],
   "Stunned": ["emoji-dizzy", 4.05, False],
   "Cursing Emote": ["emoji-cursing", 2.38, True],
   "Sob": ["emoji-crying", 3.70, False],
   "Clap": ["emoji-clapping", 2.16, False],
   "Raise The Roof": ["emoji-celebrate", 3.41, True],
   "Arrogance": ["emoji-arrogance", 6.87, False],
   "Angry": ["emoji-angry", 5.76, True],
   "Savage Dance": ["dance-tiktok8", 10.94, True],
   "Don't Start Now": ["dance-tiktok2", 10.39, True],
   "Let's Go Shopping": ["dance-shoppingcart", 4.32, True],
   "Russian Dance": ["dance-russian", 10.25, True],
   "Penny's Dance": ["dance-pennywise", 1.21, True],
   "Macarena": ["dance-macarena", 12.21, True],
   "K-Pop Dance": ["dance-blackpink", 7.15, True],
   "Hyped": ["emote-hyped", 7.49, True],
   "Jinglebell": ["dance-jinglebell", 11.00, True],
   "Nervous": ["idle-nervous", 21.71, True],
   "Toilet": ["idle-toilet", 32.17, True],
   "Astronaut": ["emote-astronaut", 13.79, True],
   "Dance Zombie": ["dance-zombie", 12.92, True],
   "Heart Eyes": ["emote-hearteyes", 4.03, True],
   "Swordfight": ["emote-swordfight", 5.91, True],
   "TimeJump": ["emote-timejump", 4.01, True],
   "Snake": ["emote-snake", 5.26, True],
   "Heart Fingers": ["emote-heartfingers", 4.00, True],
   "Float": ["emote-float", 9.00, True],
   "Telekinesis": ["emote-telekinesis", 10.49, True],
   "Penguin dance": ["dance-pinguin", 11.58, True],
   "Creepy puppet": ["dance-creepypuppet", 6.42, True],
   "Sleigh": ["emote-sleigh", 11.33, True],
   "Maniac": ["emote-maniac", 4.91, True],
   "Energy Ball": ["emote-energyball", 7.58, True],
   "Singing": ["idle_singing", 10.26, True],
   "Frog": ["emote-frog", 14.55, True],
   "Superpose": ["emote-superpose", 4.53, True],
   "Cute": ["emote-cute", 6.17, True],
   "TikTok Dance 9": ["dance-tiktok9", 11.89, True],
   "Weird Dance": ["dance-weird", 21.56, True],
   "TikTok Dance 10": ["dance-tiktok10", 8.23, True],
   "Pose 7": ["emote-pose7", 4.66, True],
   "Pose 8": ["emote-pose8", 4.81, True],
   "Casual Dance": ["idle-dance-casual", 9.08, True],
   "Pose 1": ["emote-pose1", 2.83, True],
   "Pose 3": ["emote-pose3", 5.11, True],
   "Pose 5": ["emote-pose5", 4.62, True],
   "Cutey": ["emote-cutey", 3.26, True],
   "Punk Guitar": ["emote-punkguitar", 9.37, True],
   "Fashionista": ["emote-fashionista", 5.61, True],
   "Gravity": ["emote-gravity", 8.96, True],
   "Ice Cream Dance": ["dance-icecream", 14.77, True],
   "Wrong Dance": ["dance-wrong", 12.42, True],
   "UwU": ["idle-uwu", 24.76, True],
   "TikTok Dance 4": ["idle-dance-tiktok4", 15.50, True],
   "Advanced Shy": ["emote-shy2", 4.99, True],
   "Anime Dance": ["dance-anime", 8.47, True],
   "Kawaii": ["dance-kawai", 10.29, True],
   "Scritchy": ["idle-wild", 26.42, True],
   "Ice Skating": ["emote-iceskating", 7.30, True],
   "SurpriseBig": ["emote-pose6", 5.38, True],
   "Celebration Step": ["emote-celebrationstep", 3.35, True],
   "Creepycute": ["emote-creepycute", 7.90, True],
   "Pose 10": ["emote-pose10", 3.99, True],
   "Boxer": ["emote-boxer", 5.56, True],
   "Head Blowup": ["emote-headblowup", 11.67, True],
   "Ditzy Pose": ["emote-pose9", 4.58, True],
   "Teleporting": ["emote-teleporting", 11.77, True],
   "Touch": ["dance-touch", 11.70, True],
   "Air Guitar": ["idle-guitar", 13.23, True],
   "This Is For You": ["emote-gift", 5.80, True],
   "Push it": ["dance-employee", 8.00, True],
   "Wop Dance": ["dance-tiktok11", 11.00, True],
   "Cute Salute": ["emote-cutesalute", 3.00, True],
   "At Attention": ["emote-salute", 3.00, True]
    }